import React from 'react';
import { Printer } from 'lucide-react';

export default function AveragesTable({ data }) {
  // We no longer need to sort here because the Dashboard already passed us
  // perfectly normalized and sorted data (Driver -> Wedges)!

  return (
    <div className="bg-white dark:bg-slate-900 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 p-4 md:p-6 w-full print:fixed print:inset-0 print:m-0 print:border-none print:shadow-none print:bg-white print:text-black print:z-50">
      <div className="flex justify-between items-center mb-6 print:hidden">
        <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">Yardage Averages</h2>
        <button 
          onClick={() => window.print()}
          className="flex items-center gap-2 px-3 py-1.5 text-sm bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 rounded-md hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors"
        >
          <Printer className="w-4 h-4" /> Print
        </button>
      </div>

      {/* Print-only header */}
      <div className="hidden print:block text-center mb-8">
        <h1 className="text-2xl font-bold border-b-2 border-black pb-2">My Yardage Book</h1>
        <p className="text-sm mt-2 text-gray-600">Generated by SwingLedger</p>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="border-b border-slate-200 dark:border-slate-700 print:border-black">
              <th className="py-3 px-4 font-semibold text-slate-600 dark:text-slate-400 print:text-black">Club</th>
              <th className="py-3 px-4 font-semibold text-slate-600 dark:text-slate-400 print:text-black">Avg Carry</th>
              <th className="py-3 px-4 font-semibold text-slate-600 dark:text-slate-400 print:text-black">Avg Total</th>
              <th className="py-3 px-4 font-semibold text-slate-600 dark:text-slate-400 print:text-black">Gap to Next</th>
            </tr>
          </thead>
          <tbody>
            {data.map((club, index) => {
              // Because the array is Driver -> Wedges, the "next" club is the shorter one
              const nextClub = data[index + 1];
              const gap = nextClub ? Math.round(club.carry - nextClub.carry) : '--';

              return (
                <tr key={club.club} className="border-b border-slate-100 dark:border-slate-800/50 print:border-gray-300">
                  <td className="py-3 px-4 font-bold text-emerald-600 dark:text-emerald-400 print:text-black">{club.club}</td>
                  <td className="py-3 px-4 text-slate-800 dark:text-slate-200 print:text-black">{Math.round(club.carry)} <span className="text-xs text-slate-400 print:text-gray-500">yds</span></td>
                  <td className="py-3 px-4 text-slate-800 dark:text-slate-200 print:text-black">{Math.round(club.total || club.carry)} <span className="text-xs text-slate-400 print:text-gray-500">yds</span></td>
                  <td className="py-3 px-4 text-slate-500 dark:text-slate-400 print:text-black">{gap} {gap !== '--' && <span className="text-xs">yds</span>}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}