import React from 'react';
import { Printer, Scissors } from 'lucide-react';

export default function AveragesTable({ data }) {
  // We no longer need to sort here because the Dashboard already passed us
  // perfectly normalized and sorted data (Driver -> Wedges)!

  return (
    <div className="bg-white dark:bg-slate-900 rounded-xl shadow-sm border border-slate-200 dark:border-slate-800 p-4 md:p-6 w-full print:fixed print:inset-0 print:m-0 print:border-none print:shadow-none print:bg-white print:text-black print:z-50 print:flex print:justify-center print:items-start print:pt-12">
      
      {/* Web Header */}
      <div className="flex justify-between items-center mb-6 print:hidden">
        <h2 className="text-lg font-bold text-slate-800 dark:text-slate-100">Yardage Averages</h2>
        <button 
          onClick={() => window.print()}
          className="flex items-center gap-2 px-3 py-1.5 text-sm bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 rounded-md hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors font-bold"
        >
          <Printer className="w-4 h-4" /> Print Pocket Book
        </button>
      </div>

      {/* --- PRINT ONLY: Yardage Book Cutout Box --- */}
      {/* THE FIX: Bumped the zoom scale to 1.65 (165%) */}
      <div className="print:w-[4in] print:h-fit print:border-2 print:border-dashed print:border-slate-400 print:p-4 print:relative print:[zoom:1.65]">
        
        {/* Little scissor icon to indicate cutting for the printout */}
        <div className="hidden print:block absolute -top-3 -left-3 bg-white px-1 text-slate-400">
          <Scissors className="w-4 h-4" />
        </div>

        {/* Print Header */}
        <div className="hidden print:block text-center mb-4">
          <h1 className="text-xl font-black uppercase tracking-widest border-b-2 border-black pb-2">My Yardages</h1>
          <p className="text-[10px] mt-1 font-bold text-gray-500 uppercase tracking-wider">Generated by SwingLedger</p>
        </div>

        {/* Table */}
        <div className="overflow-x-auto print:overflow-hidden">
          <table className="w-full text-left border-collapse">
            <thead>
              <tr className="border-b border-slate-200 dark:border-slate-700 print:border-black">
                <th className="py-3 px-4 print:py-1 print:px-1 font-semibold text-slate-600 dark:text-slate-400 print:text-black print:text-[10px] print:uppercase print:tracking-wider">Club</th>
                <th className="py-3 px-4 print:py-1 print:px-1 font-semibold text-slate-600 dark:text-slate-400 print:text-black print:text-[10px] print:uppercase print:tracking-wider text-center">Carry</th>
                <th className="py-3 px-4 print:py-1 print:px-1 font-semibold text-slate-600 dark:text-slate-400 print:text-black print:text-[10px] print:uppercase print:tracking-wider text-center">Total</th>
                <th className="py-3 px-4 print:py-1 print:px-1 font-semibold text-slate-600 dark:text-slate-400 print:text-black print:text-[10px] print:uppercase print:tracking-wider text-right">Gap</th>
              </tr>
            </thead>
            <tbody>
              {data.map((club, index) => {
                // Because the array is Driver -> Wedges, the "next" club is the shorter one
                const nextClub = data[index + 1];
                const gap = nextClub ? Math.round(club.carry - nextClub.carry) : '--';

                return (
                  <tr key={club.club} className="border-b border-slate-100 dark:border-slate-800/50 print:border-gray-300">
                    {/* Club Name */}
                    <td className="py-3 px-4 print:py-1.5 print:px-1 font-bold text-emerald-600 dark:text-emerald-400 print:text-black print:text-sm">
                      {club.club}
                    </td>
                    
                    {/* Carry */}
                    <td className="py-3 px-4 print:py-1.5 print:px-1 text-slate-800 dark:text-slate-200 print:text-black text-center print:text-sm font-medium">
                      {Math.round(club.carry)} <span className="text-xs text-slate-400 print:text-gray-500 print:text-[9px]">yds</span>
                    </td>
                    
                    {/* Total */}
                    <td className="py-3 px-4 print:py-1.5 print:px-1 text-slate-800 dark:text-slate-200 print:text-black text-center print:text-sm font-medium">
                      {Math.round(club.total || club.carry)} <span className="text-xs text-slate-400 print:text-gray-500 print:text-[9px]">yds</span>
                    </td>
                    
                    {/* Gap */}
                    <td className="py-3 px-4 print:py-1.5 print:px-1 text-slate-500 dark:text-slate-400 print:text-gray-600 text-right print:text-xs font-bold">
                      {gap} {gap !== '--' && <span className="text-[10px] print:font-normal">yds</span>}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}