export const OPTIMAL_TARGETS = {
  driver: {
    aoa: "Up (+2° to +5°)",
    path: "Neutral to slight In-to-out (0° to +2°)",
    face: "Near zero (−0.5° to +0.5°)",
    face_to_path: "Near zero to slightly negative (0° to −1°)"
  },
  irons: {
    aoa: "Down (−3° to −5°; wedges can be −5° to −7°)",
    path: "Neutral (−1° to +1°)",
    face: "Near zero (−0.5° to +0.5°)",
    face_to_path: "Near zero (−0.5° to +0.5°)"
  }
};

const COACHING_MATRIX = [
  // --- AOA: DOWN ---
  { aoa_state: "Down", path_state: "Out-to-in", face_state: "Closed (left)", face_to_path_state: "Zero", ball_start: "Left", curve: "None", typical_shot: "Pull-straight", tendencies: "Launch ↓, spin ↑; good for irons compression, risky for driver (pop-up/spinny).", corrections: { primary: ["Open the face slightly: neutralize/soften grip, add a bit more lead-wrist extension, feel a hold-off through impact.", "Reduce out-to-in path: close stance slightly, trail-foot back, feel the club approach from inside-to-out.", "Face-to-path near zero—good baseline for straight ball flight."], driver: ["Reduce downward AoA: tee higher, move ball forward, tilt spine away from target, feel club sweep up."], irons: ["Keep a controlled downward strike: ball slightly forward of center with larger clubs, shift pressure left before impact, compress then brush turf."] } },
  { aoa_state: "Down", path_state: "Out-to-in", face_state: "Square", face_to_path_state: "Positive (fade bias)", ball_start: "Straight", curve: "Right", typical_shot: "Straight-fade", tendencies: "Launch ↓, spin ↑; good for irons compression, risky for driver (pop-up/spinny).", corrections: { primary: ["Reduce out-to-in path: close stance slightly, trail-foot back, feel the club approach from inside-to-out.", "Face-to-path is positive (fade/slice). Options: close the face a touch OR shift path a bit more right—do one at a time."], driver: ["Reduce downward AoA: tee higher, move ball forward, tilt spine away from target, feel club sweep up."], irons: ["Keep a controlled downward strike: ball slightly forward of center with larger clubs, shift pressure left before impact, compress then brush turf."] } },
  { aoa_state: "Down", path_state: "Out-to-in", face_state: "Open (right)", face_to_path_state: "Positive (fade bias)", ball_start: "Right", curve: "Right", typical_shot: "Push-slice", tendencies: "Launch ↓, spin ↑; good for irons compression, risky for driver (pop-up/spinny).", corrections: { primary: ["Close the face: slightly stronger lead-hand grip, more lead-wrist flexion (bow) through impact, ensure release.", "Reduce out-to-in path: close stance slightly, trail-foot back, feel the club approach from inside-to-out.", "Face-to-path is positive (fade/slice). Options: close the face a touch OR shift path a bit more right—do one at a time."], driver: ["Reduce downward AoA: tee higher, move ball forward, tilt spine away from target, feel club sweep up."], irons: ["Keep a controlled downward strike: ball slightly forward of center with larger clubs, shift pressure left before impact, compress then brush turf."] } },
  { aoa_state: "Down", path_state: "Neutral", face_state: "Closed (left)", face_to_path_state: "Negative (draw bias)", ball_start: "Left", curve: "Left", typical_shot: "Pull-hook", tendencies: "Launch ↓, spin ↑; good for irons compression, risky for driver (pop-up/spinny).", corrections: { primary: ["Open the face slightly: neutralize/soften grip, add a bit more lead-wrist extension, feel a hold-off through impact.", "Face-to-path is negative (draw/hook). Options: open the face a touch OR shift path a bit more left—do one at a time."], driver: ["Reduce downward AoA: tee higher, move ball forward, tilt spine away from target, feel club sweep up."], irons: ["Keep a controlled downward strike: ball slightly forward of center with larger clubs, shift pressure left before impact, compress then brush turf."] } },
  { aoa_state: "Down", path_state: "Neutral", face_state: "Square", face_to_path_state: "Zero", ball_start: "Straight", curve: "None", typical_shot: "Straight", tendencies: "Launch ↓, spin ↑; good for irons compression, risky for driver (pop-up/spinny).", corrections: { primary: ["Face-to-path near zero—good baseline for straight ball flight."], driver: ["Reduce downward AoA: tee higher, move ball forward, tilt spine away from target, feel club sweep up."], irons: ["Keep a controlled downward strike: ball slightly forward of center with larger clubs, shift pressure left before impact, compress then brush turf."] } },
  { aoa_state: "Down", path_state: "Neutral", face_state: "Open (right)", face_to_path_state: "Positive (fade bias)", ball_start: "Right", curve: "Right", typical_shot: "Push-slice", tendencies: "Launch ↓, spin ↑; good for irons compression, risky for driver (pop-up/spinny).", corrections: { primary: ["Close the face: slightly stronger lead-hand grip, more lead-wrist flexion (bow) through impact, ensure release.", "Face-to-path is positive (fade/slice). Options: close the face a touch OR shift path a bit more right—do one at a time."], driver: ["Reduce downward AoA: tee higher, move ball forward, tilt spine away from target, feel club sweep up."], irons: ["Keep a controlled downward strike: ball slightly forward of center with larger clubs, shift pressure left before impact, compress then brush turf."] } },
  { aoa_state: "Down", path_state: "In-to-out", face_state: "Closed (left)", face_to_path_state: "Negative (draw bias)", ball_start: "Left", curve: "Left", typical_shot: "Pull-hook", tendencies: "Launch ↓, spin ↑; good for irons compression, risky for driver (pop-up/spinny).", corrections: { primary: ["Open the face slightly: neutralize/soften grip, add a bit more lead-wrist extension, feel a hold-off through impact.", "Reduce in-to-out path: align a touch left, feel lead-hip opening earlier, swing more 'left' through impact.", "Face-to-path is negative (draw/hook). Options: open the face a touch OR shift path a bit more left—do one at a time."], driver: ["Reduce downward AoA: tee higher, move ball forward, tilt spine away from target, feel club sweep up."], irons: ["Keep a controlled downward strike: ball slightly forward of center with larger clubs, shift pressure left before impact, compress then brush turf."] } },
  { aoa_state: "Down", path_state: "In-to-out", face_state: "Square", face_to_path_state: "Negative (draw bias)", ball_start: "Straight", curve: "Left", typical_shot: "Straight-draw", tendencies: "Launch ↓, spin ↑; good for irons compression, risky for driver (pop-up/spinny).", corrections: { primary: ["Reduce in-to-out path: align a touch left, feel lead-hip opening earlier, swing more 'left' through impact.", "Face-to-path is negative (draw/hook). Options: open the face a touch OR shift path a bit more left—do one at a time."], driver: ["Reduce downward AoA: tee higher, move ball forward, tilt spine away from target, feel club sweep up."], irons: ["Keep a controlled downward strike: ball slightly forward of center with larger clubs, shift pressure left before impact, compress then brush turf."] } },
  { aoa_state: "Down", path_state: "In-to-out", face_state: "Open (right)", face_to_path_state: "Zero", ball_start: "Right", curve: "None", typical_shot: "Push-straight", tendencies: "Launch ↓, spin ↑; good for irons compression, risky for driver (pop-up/spinny).", corrections: { primary: ["Close the face: slightly stronger lead-hand grip, more lead-wrist flexion (bow) through impact, ensure release.", "Reduce in-to-out path: align a touch left, feel lead-hip opening earlier, swing more 'left' through impact.", "Face-to-path near zero—good baseline for straight ball flight."], driver: ["Reduce downward AoA: tee higher, move ball forward, tilt spine away from target, feel club sweep up."], irons: ["Keep a controlled downward strike: ball slightly forward of center with larger clubs, shift pressure left before impact, compress then brush turf."] } },

  // --- AOA: NEUTRAL ---
  { aoa_state: "Neutral", path_state: "Out-to-in", face_state: "Closed (left)", face_to_path_state: "Zero", ball_start: "Left", curve: "None", typical_shot: "Pull-straight", tendencies: "Neutral launch/spin; fine baseline but club-dependent.", corrections: { primary: ["Open the face slightly: neutralize/soften grip, add a bit more lead-wrist extension, feel a hold-off through impact.", "Reduce out-to-in path: close stance slightly, trail-foot back, feel the club approach from inside-to-out.", "Face-to-path near zero—good baseline for straight ball flight."], driver: ["Nudge AoA slightly up for driver: small setup tilt and higher tee."], irons: ["Nudge AoA slightly down for irons: small ball-back shift and earlier lead-side pressure."] } },
  { aoa_state: "Neutral", path_state: "Out-to-in", face_state: "Square", face_to_path_state: "Positive (fade bias)", ball_start: "Straight", curve: "Right", typical_shot: "Straight-fade", tendencies: "Neutral launch/spin; fine baseline but club-dependent.", corrections: { primary: ["Reduce out-to-in path: close stance slightly, trail-foot back, feel the club approach from inside-to-out.", "Face-to-path is positive (fade/slice). Options: close the face a touch OR shift path a bit more right—do one at a time."], driver: ["Nudge AoA slightly up for driver: small setup tilt and higher tee."], irons: ["Nudge AoA slightly down for irons: small ball-back shift and earlier lead-side pressure."] } },
  { aoa_state: "Neutral", path_state: "Out-to-in", face_state: "Open (right)", face_to_path_state: "Positive (fade bias)", ball_start: "Right", curve: "Right", typical_shot: "Push-slice", tendencies: "Neutral launch/spin; fine baseline but club-dependent.", corrections: { primary: ["Close the face: slightly stronger lead-hand grip, more lead-wrist flexion (bow) through impact, ensure release.", "Reduce out-to-in path: close stance slightly, trail-foot back, feel the club approach from inside-to-out.", "Face-to-path is positive (fade/slice). Options: close the face a touch OR shift path a bit more right—do one at a time."], driver: ["Nudge AoA slightly up for driver: small setup tilt and higher tee."], irons: ["Nudge AoA slightly down for irons: small ball-back shift and earlier lead-side pressure."] } },
  { aoa_state: "Neutral", path_state: "Neutral", face_state: "Closed (left)", face_to_path_state: "Negative (draw bias)", ball_start: "Left", curve: "Left", typical_shot: "Pull-hook", tendencies: "Neutral launch/spin; fine baseline but club-dependent.", corrections: { primary: ["Open the face slightly: neutralize/soften grip, add a bit more lead-wrist extension, feel a hold-off through impact.", "Face-to-path is negative (draw/hook). Options: open the face a touch OR shift path a bit more left—do one at a time."], driver: ["Nudge AoA slightly up for driver: small setup tilt and higher tee."], irons: ["Nudge AoA slightly down for irons: small ball-back shift and earlier lead-side pressure."] } },
  { aoa_state: "Neutral", path_state: "Neutral", face_state: "Square", face_to_path_state: "Zero", ball_start: "Straight", curve: "None", typical_shot: "Straight", tendencies: "Neutral launch/spin; fine baseline but club-dependent.", corrections: { primary: ["Face-to-path near zero—good baseline for straight ball flight."], driver: ["Nudge AoA slightly up for driver: small setup tilt and higher tee."], irons: ["Nudge AoA slightly down for irons: small ball-back shift and earlier lead-side pressure."] } },
  { aoa_state: "Neutral", path_state: "Neutral", face_state: "Open (right)", face_to_path_state: "Positive (fade bias)", ball_start: "Right", curve: "Right", typical_shot: "Push-slice", tendencies: "Neutral launch/spin; fine baseline but club-dependent.", corrections: { primary: ["Close the face: slightly stronger lead-hand grip, more lead-wrist flexion (bow) through impact, ensure release.", "Face-to-path is positive (fade/slice). Options: close the face a touch OR shift path a bit more right—do one at a time."], driver: ["Nudge AoA slightly up for driver: small setup tilt and higher tee."], irons: ["Nudge AoA slightly down for irons: small ball-back shift and earlier lead-side pressure."] } },
  { aoa_state: "Neutral", path_state: "In-to-out", face_state: "Closed (left)", face_to_path_state: "Negative (draw bias)", ball_start: "Left", curve: "Left", typical_shot: "Pull-hook", tendencies: "Neutral launch/spin; fine baseline but club-dependent.", corrections: { primary: ["Open the face slightly: neutralize/soften grip, add a bit more lead-wrist extension, feel a hold-off through impact.", "Reduce in-to-out path: align a touch left, feel lead-hip opening earlier, swing more 'left' through impact.", "Face-to-path is negative (draw/hook). Options: open the face a touch OR shift path a bit more left—do one at a time."], driver: ["Nudge AoA slightly up for driver: small setup tilt and higher tee."], irons: ["Nudge AoA slightly down for irons: small ball-back shift and earlier lead-side pressure."] } },
  { aoa_state: "Neutral", path_state: "In-to-out", face_state: "Square", face_to_path_state: "Negative (draw bias)", ball_start: "Straight", curve: "Left", typical_shot: "Straight-draw", tendencies: "Neutral launch/spin; fine baseline but club-dependent.", corrections: { primary: ["Reduce in-to-out path: align a touch left, feel lead-hip opening earlier, swing more 'left' through impact.", "Face-to-path is negative (draw/hook). Options: open the face a touch OR shift path a bit more left—do one at a time."], driver: ["Nudge AoA slightly up for driver: small setup tilt and higher tee."], irons: ["Nudge AoA slightly down for irons: small ball-back shift and earlier lead-side pressure."] } },
  { aoa_state: "Neutral", path_state: "In-to-out", face_state: "Open (right)", face_to_path_state: "Zero", ball_start: "Right", curve: "None", typical_shot: "Push-straight", tendencies: "Neutral launch/spin; fine baseline but club-dependent.", corrections: { primary: ["Close the face: slightly stronger lead-hand grip, more lead-wrist flexion (bow) through impact, ensure release.", "Reduce in-to-out path: align a touch left, feel lead-hip opening earlier, swing more 'left' through impact.", "Face-to-path near zero—good baseline for straight ball flight."], driver: ["Nudge AoA slightly up for driver: small setup tilt and higher tee."], irons: ["Nudge AoA slightly down for irons: small ball-back shift and earlier lead-side pressure."] } },

  // --- AOA: UP ---
  { aoa_state: "Up", path_state: "Out-to-in", face_state: "Closed (left)", face_to_path_state: "Zero", ball_start: "Left", curve: "None", typical_shot: "Pull-straight", tendencies: "Launch ↑, spin ↓ (driver); risk thin/heel with irons if too shallow.", corrections: { primary: ["Open the face slightly: neutralize/soften grip, add a bit more lead-wrist extension, feel a hold-off through impact.", "Reduce out-to-in path: close stance slightly, trail-foot back, feel the club approach from inside-to-out.", "Face-to-path near zero—good baseline for straight ball flight."], driver: ["Maintain upward AoA: tee high, ball forward, slight trail-shoulder lower, keep head behind ball."], irons: ["If irons get too shallow: move ball a hair back, feel lead side pressure earlier, brush turf after ball."] } },
  { aoa_state: "Up", path_state: "Out-to-in", face_state: "Square", face_to_path_state: "Positive (fade bias)", ball_start: "Straight", curve: "Right", typical_shot: "Straight-fade", tendencies: "Launch ↑, spin ↓ (driver); risk thin/heel with irons if too shallow.", corrections: { primary: ["Reduce out-to-in path: close stance slightly, trail-foot back, feel the club approach from inside-to-out.", "Face-to-path is positive (fade/slice). Options: close the face a touch OR shift path a bit more right—do one at a time."], driver: ["Maintain upward AoA: tee high, ball forward, slight trail-shoulder lower, keep head behind ball."], irons: ["If irons get too shallow: move ball a hair back, feel lead side pressure earlier, brush turf after ball."] } },
  { aoa_state: "Up", path_state: "Out-to-in", face_state: "Open (right)", face_to_path_state: "Positive (fade bias)", ball_start: "Right", curve: "Right", typical_shot: "Push-slice", tendencies: "Launch ↑, spin ↓ (driver); risk thin/heel with irons if too shallow.", corrections: { primary: ["Close the face: slightly stronger lead-hand grip, more lead-wrist flexion (bow) through impact, ensure release.", "Reduce out-to-in path: close stance slightly, trail-foot back, feel the club approach from inside-to-out.", "Face-to-path is positive (fade/slice). Options: close the face a touch OR shift path a bit more right—do one at a time."], driver: ["Maintain upward AoA: tee high, ball forward, slight trail-shoulder lower, keep head behind ball."], irons: ["If irons get too shallow: move ball a hair back, feel lead side pressure earlier, brush turf after ball."] } },
  { aoa_state: "Up", path_state: "Neutral", face_state: "Closed (left)", face_to_path_state: "Negative (draw bias)", ball_start: "Left", curve: "Left", typical_shot: "Pull-hook", tendencies: "Launch ↑, spin ↓ (driver); risk thin/heel with irons if too shallow.", corrections: { primary: ["Open the face slightly: neutralize/soften grip, add a bit more lead-wrist extension, feel a hold-off through impact.", "Face-to-path is negative (draw/hook). Options: open the face a touch OR shift path a bit more left—do one at a time."], driver: ["Maintain upward AoA: tee high, ball forward, slight trail-shoulder lower, keep head behind ball."], irons: ["If irons get too shallow: move ball a hair back, feel lead side pressure earlier, brush turf after ball."] } },
  { aoa_state: "Up", path_state: "Neutral", face_state: "Square", face_to_path_state: "Zero", ball_start: "Straight", curve: "None", typical_shot: "Straight", tendencies: "Launch ↑, spin ↓ (driver); risk thin/heel with irons if too shallow.", corrections: { primary: ["Face-to-path near zero—good baseline for straight ball flight."], driver: ["Maintain upward AoA: tee high, ball forward, slight trail-shoulder lower, keep head behind ball."], irons: ["If irons get too shallow: move ball a hair back, feel lead side pressure earlier, brush turf after ball."] } },
  { aoa_state: "Up", path_state: "Neutral", face_state: "Open (right)", face_to_path_state: "Positive (fade bias)", ball_start: "Right", curve: "Right", typical_shot: "Push-slice", tendencies: "Launch ↑, spin ↓ (driver); risk thin/heel with irons if too shallow.", corrections: { primary: ["Close the face: slightly stronger lead-hand grip, more lead-wrist flexion (bow) through impact, ensure release.", "Face-to-path is positive (fade/slice). Options: close the face a touch OR shift path a bit more right—do one at a time."], driver: ["Maintain upward AoA: tee high, ball forward, slight trail-shoulder lower, keep head behind ball."], irons: ["If irons get too shallow: move ball a hair back, feel lead side pressure earlier, brush turf after ball."] } },
  { aoa_state: "Up", path_state: "In-to-out", face_state: "Closed (left)", face_to_path_state: "Negative (draw bias)", ball_start: "Left", curve: "Left", typical_shot: "Pull-hook", tendencies: "Launch ↑, spin ↓ (driver); risk thin/heel with irons if too shallow.", corrections: { primary: ["Open the face slightly: neutralize/soften grip, add a bit more lead-wrist extension, feel a hold-off through impact.", "Reduce in-to-out path: align a touch left, feel lead-hip opening earlier, swing more 'left' through impact.", "Face-to-path is negative (draw/hook). Options: open the face a touch OR shift path a bit more left—do one at a time."], driver: ["Maintain upward AoA: tee high, ball forward, slight trail-shoulder lower, keep head behind ball."], irons: ["If irons get too shallow: move ball a hair back, feel lead side pressure earlier, brush turf after ball."] } },
  { aoa_state: "Up", path_state: "In-to-out", face_state: "Square", face_to_path_state: "Negative (draw bias)", ball_start: "Straight", curve: "Left", typical_shot: "Straight-draw", tendencies: "Launch ↑, spin ↓ (driver); risk thin/heel with irons if too shallow.", corrections: { primary: ["Reduce in-to-out path: align a touch left, feel lead-hip opening earlier, swing more 'left' through impact.", "Face-to-path is negative (draw/hook). Options: open the face a touch OR shift path a bit more left—do one at a time."], driver: ["Maintain upward AoA: tee high, ball forward, slight trail-shoulder lower, keep head behind ball."], irons: ["If irons get too shallow: move ball a hair back, feel lead side pressure earlier, brush turf after ball."] } },
  { aoa_state: "Up", path_state: "In-to-out", face_state: "Open (right)", face_to_path_state: "Zero", ball_start: "Right", curve: "None", typical_shot: "Push-straight", tendencies: "Launch ↑, spin ↓ (driver); risk thin/heel with irons if too shallow.", corrections: { primary: ["Close the face: slightly stronger lead-hand grip, more lead-wrist flexion (bow) through impact, ensure release.", "Reduce in-to-out path: align a touch left, feel lead-hip opening earlier, swing more 'left' through impact.", "Face-to-path near zero—good baseline for straight ball flight."], driver: ["Maintain upward AoA: tee high, ball forward, slight trail-shoulder lower, keep head behind ball."], irons: ["If irons get too shallow: move ball a hair back, feel lead side pressure earlier, brush turf after ball."] } }
];

export const getSwingDiagnosis = (metrics) => {
  if (!metrics) return null;

  // Convert raw degrees into state strings
  const aoaState = metrics.avgAoa < -1 ? "Down" : metrics.avgAoa > 1 ? "Up" : "Neutral";
  const pathState = metrics.avgPath < -1 ? "Out-to-in" : metrics.avgPath > 1 ? "In-to-out" : "Neutral";
  const faceState = metrics.avgFtt < -1 ? "Closed (left)" : metrics.avgFtt > 1 ? "Open (right)" : "Square";

  // Find the matching combination in our coaching matrix
  const match = COACHING_MATRIX.find(c => 
    c.aoa_state === aoaState && 
    c.path_state === pathState && 
    c.face_state === faceState
  );

  return match || null;
};